#!/usr/bin/env bash
# This script displays hours 0 to 12 and minutes 1 to 59

hour=0

while [ "$hour" -le 12 ]
do
    if [ "$hour" -eq 0 ]
    then
        echo "Hour: 0"
    else
        echo "Hour: $hour"
    fi

    minute=1
    while [ "$minute" -le 59 ]
    do
        echo "$minute"
        minute=$((minute + 1))
    done

    hour=$((hour + 1))
done
