#!/bin/bash
echo "obase=8;$(echo $WATER | tr 'water' '01234' | tr '[:lower:]' '[:upper:]' | sed 's/^/ibase=5;/;s/$/+/') $(echo $STIR | tr 'stir.' '01234' | tr '[:lower:]' '[:upper:]' | sed 's/^/ibase=5;/;s/$/ /')" | bc | tr '01234567' 'bestchol'
